### PR TITLE
Denoise profiled and rawdenoise

### PR DESCRIPTION
**Pull request by rawfiner**
Some explanations about denoise profiled and rawdenoise.
My image I used for denoising examples is available here:
https://drive.google.com/open?id=1zVeIw3aE9MNKEKjBURQ-VbTaaS1Yl7Jf

### CODE REVIEW

**Comment by moy** [comment]
Very welcome indeed :-). There are too many new features in 2.6, it's an endless task to document them.

I'll tweak the text a little after merging. Don't hesitate to say so if you disagree with my changes.

**Comment by rawfiner** [comment]
No problem :-) Don't hesitate if you have any question

**Comment by moy** [comment]
The images are too large for dt's website, and are rescaled when displayed => we don't see the noise properly.

See: http://matthieu-moy.fr/tmp/2018/wip-dt/2018/12/darktable-26/#denoise

Can you make screenshots with width < 768 pixels? (eg. 700 pixels wide)

**Comment by rawfiner** [comment]
Indeed. Ok I'll do that

**Comment by moy** [comment]
BTW, as much as possible send a message (e.g. file a new issue) before starting to work, so that we avoid writing the same section at the same time (we've been lucky here, I hadn't started anything).

**Comment by rawfiner** [comment]
That is indeed a good point. I will do that in the future

**Pull request merged**
